openapi: 3.0.0
info:
  title: ExerciseAPI
  version: '1.0'
  contact:
    name: Jake Wickstrom
    email: jtwickstrom@gmail.com
  description: API for interacting with Exercise related elements of the Spottr application
servers:
  - url: 'http://localhost:3000'
    description: Jake Wickstrom
paths:
  /exercises:
    get:
      summary: Get Exercises
      tags:
        - exercises
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'
      operationId: get-exercises
      description: Get exercises
      parameters:
        - schema:
            type: string
          in: query
          name: mgroup
          description: The muscle group(s) the returned exercies should work
  '/users/{userID}/plans/recommended':
    parameters:
      - schema:
          type: string
        name: userID
        in: path
        required: true
    get:
      summary: Get Recommended Plan
      tags:
        - plans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
      operationId: get-users-userID-plans-recommended
      description: Reccomends a new workout plan for a user
  '/users/{userID}/plans':
    parameters:
      - schema:
          type: string
        name: userID
        in: path
        required: true
    get:
      summary: Get Saved Plans By User
      tags:
        - plans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plan'
      operationId: get-users-userID-plans
      description: Get plans created by a specific user
  /plans:
    get:
      summary: Get Plans
      tags:
        - plans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plan'
      operationId: get-plans
      description: Get a list of plans
      parameters:
        - schema:
            type: string
          in: query
          name: minduration
          description: Only returns plans with a estimated duration longer than minduration
        - schema:
            type: string
          in: query
          name: maxduration
          description: Only returns plans with an estimated duration shorted than maxduration
    post:
      summary: Create New Plan
      operationId: post-plans
      responses:
        '200':
          description: OK
      description: 'Create a new plan to use later, or to be used by other users'
      tags:
        - plans
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plan'
  '/plans/{planID}':
    parameters:
      - schema:
          type: string
        name: planID
        in: path
        required: true
    get:
      summary: Get Plan By ID
      tags:
        - plans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plan'
      operationId: get-plans-planID
      description: Get a plan with the specified ID
components:
  schemas:
    Exercise:
      title: Exercise
      type: object
      x-tags:
        - models
      properties:
        id:
          type: string
        mgroup:
          type: string
    Plan:
      title: Plan
      type: object
      description: A series of routines to be performed by a user
      x-tags:
        - models
      properties:
        id:
          type: string
        routines:
          type: array
          items:
            $ref: '#/components/schemas/Routine'
        name:
          type: string
        authorID:
          type: string
        isPublic:
          type: boolean
      required:
        - routines
        - authorID
        - isPublic
    Routine:
      title: Routine
      type: object
      description: |-
        A specification of how to much of a single exercise that was/will be performed and how much rest should be taken in between

        ex: A routine may consist of 3 sets of bench press, with 8 reps each
        ex: A routine may consist of 3 intervals of 2 mins on the treadmill at 12 km/h with 2 mins rest
      properties:
        id:
          type: string
        exerciseID:
          type: string
        reps:
          type: number
        sets:
          type: number
        durationRoutine:
          type: boolean
        duration:
          type: number
        rest:
          type: number
      required:
        - exerciseID
        - durationRoutine
      x-tags:
        - models
tags:
  - name: plans
  - name: exercises
