version: '2.1'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    command: /bin/bash ./entrypoint.sh
    ports:
      - '1433:1433'
    environment:
      - SA_PASSWORD=Password123!
      - ACCEPT_EULA=Y
    volumes:
      - dbdata:/var/opt/mssql
      - ./docker-entrypoint.sh:/entrypoint.sh
      - ./db-init.sh:/db-init.sh
      - ./db-init.sql:/db-init.sql

volumes:
  dbdata: